# Generated by Django 3.2.9 on 2021-11-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarphonesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('construction', models.CharField(max_length=50, verbose_name='Конструкция')),
                ('wireless', models.BooleanField()),
                ('frequency', models.CharField(max_length=100, verbose_name='Частотный дипозон')),
                ('sensitivities', models.CharField(max_length=60, verbose_name='Чувствительность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeakersProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('type', models.CharField(choices=[('Bluetooth - колонка', 'BT'), ('Умная колонка', 'SMART'), ('Проводная колонка', 'USUAL')], max_length=50, verbose_name='Тип')),
                ('RMS', models.CharField(max_length=60, verbose_name='Мощность')),
                ('frequency', models.CharField(max_length=100, verbose_name='Частотный дипозон')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Earphones',
        ),
    ]
