# Generated by Django 3.2.9 on 2021-11-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211103_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='earphonesproduct',
            name='wireless',
            field=models.BooleanField(default=False, verbose_name='Беспроводные'),
        ),
        migrations.AlterField(
            model_name='speakersproduct',
            name='type',
            field=models.CharField(choices=[('Bluetooth - колонка', 'Bluetooth - колонка'), ('Умная колонка', 'Умная колонка'), ('Проводная колонка', 'Проводная колонка')], max_length=50, verbose_name='Тип'),
        ),
    ]
